<?php
/**
 * BankInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ReceiptsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\ReceiptsV1;

/**
 * BankInformationTest Class Doc Comment
 *
 * @category    Class
 * @description BankInformation
 * @package     EzzeSiftuz\ReceiptsV1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BankInformation"
     */
    public function testBankInformation()
    {
    }

    /**
     * Test attribute "account_owner"
     */
    public function testPropertyAccountOwner()
    {
    }

    /**
     * Test attribute "bank_name"
     */
    public function testPropertyBankName()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }
}
