<?php
/**
 * ShippingCost1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ReceiptsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\ReceiptsV1;

/**
 * ShippingCost1Test Class Doc Comment
 *
 * @category    Class
 * @description ShippingCost1
 * @package     EzzeSiftuz\ReceiptsV1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingCost1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingCost1"
     */
    public function testShippingCost1()
    {
    }

    /**
     * Test attribute "delivery_fee_standard"
     */
    public function testPropertyDeliveryFeeStandard()
    {
    }

    /**
     * Test attribute "delivery_fee_freight_surcharge"
     */
    public function testPropertyDeliveryFeeFreightSurcharge()
    {
    }
}
