<?php
/**
 * ReceiptsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ReceiptsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\ReceiptsV1;

use EzzeSiftuz\ReceiptsV1\Configuration;
use EzzeSiftuz\ReceiptsV1\ApiException;
use EzzeSiftuz\ReceiptsV1\ObjectSerializer;

/**
 * ReceiptsApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\ReceiptsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReceiptsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getReceiptPdfUsingGET
     *
     * Get the PDF document of a specific receipt by receipt number. It's valid only for purchase receipts for now..
     *
     */
    public function testGetReceiptPdfUsingGET()
    {
    }

    /**
     * Test case for getReceiptUsingGET
     *
     * Get a specific receipt for the given receipt number as JSON object.
     *
     */
    public function testGetReceiptUsingGET()
    {
    }

    /**
     * Test case for getReceiptsUsingGET
     *
     * Get all receipts as list of JSON objects.
     *
     */
    public function testGetReceiptsUsingGET()
    {
    }
}
